---
name: Checkov
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_2 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_2 }}
          aws-region: eu-west-3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Update kube config
        run: |
          pwd & ls
          cat ./k8s/*.yaml | sed 's#\${REPOSITORY_PREFIX_EL}'"#${REPOSITORY_PREFIX_EL}#g" | > deploy.yaml

     # - name: Test with Checkov
      #  id: checkov
       # uses: bridgecrewio/checkov-action@master
        #with:
         # directory: ./
          #framework: terraform 

      - name: Check out code
        uses: actions/checkout@v2
      - name: Install utilities
        run: |
          sudo apt install -y gettext
          mkdir -p ${HOME}/.local/bin
          wget -q https://github.com/jckuester/awsweeper/releases/download/v0.12.0/awsweeper_0.12.0_linux_amd64.tar.gz
          tar zxf awsweeper_0.12.0_linux_amd64.tar.gz
          mv awsweeper_0.12.0_linux_amd64/awsweeper ${HOME}/.local/bin

          wget -q https://github.com/eksctl-io/eksctl/releases/download/v0.164.0/eksctl_Linux_amd64.tar.gz
          tar zxf eksctl_Linux_amd64.tar.gz
          mv eksctl ${HOME}/.local/bin
          chmod +x ${HOME}/.local/bin/*
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Set cluster ID
        env:
          RUN_ID: "${{ github.job }}"
          AWS_REGION: "${{ secrets.AWS_REGION }}"
        run: |
          CLUSTER_ID=$(echo $RANDOM | md5sum | head -c 8)
          echo "Using cluster ID ${CLUSTER_ID}"
          echo "CLUSTER_ID=$CLUSTER_ID" >> $GITHUB_ENV

      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
            role-to-assume: test
            role-duration-seconds: 3600
            aws-region: eu-west-3
            role-session-name: GithubActionsSession-${{ env.CLUSTER_ID }}

      - name: Create infrastructure
        id: create-infrastructure
        env:
         AWS_REGION: eu-west-3
        run: |
         make create-infrastructure environment="$CLUSTER_ID"

      
